# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pPKXmoYpUoC1BubUlOHjaEkALFqvgxcR
"""

n=float(input("enter basic salary: "))

def gross(n):
  g=n+0.1*n+0.12*n
  return g

gross(n)